apiVersion: v1
kind: ConfigMap
metadata:
  name: uascloud-config
  namespace: default
data:
  DB_HOST: "uascloud-db-service"
  DB_USER: "nops_admin"
  DB_NAME: "nops_db"
  AI_SERVICE_URL: "http://uascloud-ai-service:5000/estimate-calorie"
